
name: Notify To Telegram Group

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Send Receipt to Telegram Group
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          镜像构建完成

          镜像标签: 1
          CommitSha1: 2
          ImageDigest: 3
