
name: Notify To Telegram Group

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Telegram Message Notify
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          The ${{ github.event_name }} event triggered final step.
          echo This event is a pull request that had an assignee removed.
